#!/bin/bash

# Script to convert all Architecture.css className references to vanilla-extract styles

# Map of old className to new style name
declare -A classMap=(
  ["tree-node"]="treeNode"
  ["tree-item"]="treeItem"
  ["tree-toggle"]="treeToggle"
  ["tree-label"]="treeLabel"
  ["tree-badge"]="treeBadge"
  ["tree-file"]="treeFile"
  ["tree-children"]="treeChildren"
  ["indexing-demo"]="indexingDemo"
  ["demo-header"]="demoHeader"
  ["demo-title"]="demoTitle"
  ["demo-status"]="demoStatus"
  ["demo-body"]="demoBody"
  ["query-builder"]="queryBuilder"
  ["query-line"]="queryLine"
  ["query-keyword"]="queryKeyword"
  ["query-dot"]="queryDot"
  ["query-method"]="queryMethod"
  ["query-paren"]="queryParen"
  ["query-string"]="queryString"
  ["query-comma"]="queryComma"
  ["query-param"]="queryParam"
  ["query-colon"]="queryColon"
  ["query-value"]="queryValue"
  ["controls-row"]="controlsRow"
  ["control-group"]="controlGroup"
  ["button-group"]="buttonGroup"
  ["response-block"]="responseBlock"
  ["response-header"]="responseHeader"
  ["response-time"]="responseTime"
  ["response-body"]="responseBody"
  ["response-line"]="responseLine"
  ["response-brace"]="responseBrace"
  ["response-key"]="responseKey"
  ["response-colon"]="responseColon"
  ["response-comma"]="responseComma"
  ["response-number"]="responseNumber"
  ["response-string"]="responseString"
  ["fallback-notice"]="fallbackNotice"
  ["notice-icon"]="noticeIcon"
  ["tier-explanation"]="tierExplanation"
  ["precedence-visual"]="precedenceVisual"
  ["precedence-label"]="precedenceLabel"
  ["precedence-chain"]="precedenceChain"
  ["precedence-node"]="precedenceNode"
  ["node-num"]="nodeNum"
  ["node-name"]="nodeName"
  ["precedence-connector"]="precedenceConnector"
  ["code-content"]="codeContent"
  ["code-footer"]="codeFooter"
  ["code-ref"]="codeRef"
)

echo "This script shows what changes would be made."
echo "Run manually to see the mapping."
